# Site settings
title: Marco Paulo Front End Enginner
email: markoskt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi!, i`m a 23 years oldFront End Enginner that currently works in University Federal of Minas Gerais.
  Along for these years i have gained a large body of experience across many web technologies both client and server side.
  Ever focused heavily in front­end performance, scalability, architecture and maintainability.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devmarco.github.io" # the base hostname & protocol for your site
twitter_username: devmarco
github_username:  devmarco

# Build settings
markdown: kramdown
