# Site settings
title: Marco Paulo - A Front-end engineer based in Belo Horizonte
email: markoskt@gmail.com
description: "Front End Engineer whose focus is performance, scalability, architecture and maintainability of web projects"
keywords: "Javascript, HTML5, AngularJS, CSS"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devmarco.github.io" # the base hostname & protocol for your site
twitter_username: devmarco
github_username:  devmarco

# Build settings
markdown: kramdown
sass:
    style: :compressed

# Permalinks
permalink: :title